name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      # Installez les dépendances avant d'exécuter ESLint
      - name: Install dependencies
        run: npm ci

      # Exécutez ESLint après l'installation des dépendances
      - name: Run ESLint
        uses: stefanoeb/eslint-action@1.0.2
        with:
          files: "."  # Vérifiez le dossier ou les fichiers à analyser

      # Étape de build (si nécessaire)
      - name: Build project
        run: npm run build --if-present

      # Étape de tests (décommenter si des tests sont présents)
      # - name: Run tests
      #   run: npm test
